import type { Metadata } from "next";
import "./globals.css";
import { Lora } from 'next/font/google'

const lora = Lora({
  subsets: ['latin'],
  weight: ['400','600','700'],
})

export const metadata: Metadata = {
  title: "London Stock Exchange",
  description: "Generated by Zulaica Emiliano",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lora.className}>
        {children}
      </body>
    </html>
  );
}
